[build]
  command = "npm run build"
  functions = "dist"
  publish = "dist/public"
  environment = { VITE_API_URL = "https://web-production-ba609.up.railway.app" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
